# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/fileService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/fileService.proto\x12\x0b\x66ileservice\"`\n\x08\x46ileData\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\r\n\x05seqNo\x18\x04 \x01(\x05\x12\x13\n\x0breplicaNode\x18\x05 \x01(\t\"/\n\x08MetaData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tseqValues\x18\x02 \x01(\x0c\"\'\n\x03\x61\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\x08UserInfo\x12\x10\n\x08username\x18\x01 \x01(\t\"=\n\x08\x46ileInfo\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\r\n\x05seqNo\x18\x03 \x01(\x05\"%\n\x10\x46ileListResponse\x12\x11\n\tFilenames\x18\x01 \x01(\t\"<\n\x0b\x43lusterInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\x13\n\x0b\x63lusterName\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\"G\n\x0c\x43lusterStats\x12\x11\n\tcpu_usage\x18\x01 \x01(\t\x12\x12\n\ndisk_space\x18\x02 \x01(\t\x12\x10\n\x08used_mem\x18\x03 \x01(\t2\xe3\x04\n\x0b\x46ileservice\x12\x37\n\nUploadFile\x12\x15.fileservice.FileData\x1a\x10.fileservice.ack(\x01\x12>\n\x0c\x44ownloadFile\x12\x15.fileservice.FileInfo\x1a\x15.fileservice.FileData0\x01\x12\x35\n\nFileSearch\x12\x15.fileservice.FileInfo\x1a\x10.fileservice.ack\x12:\n\rReplicateFile\x12\x15.fileservice.FileData\x1a\x10.fileservice.ack(\x01\x12@\n\x08\x46ileList\x12\x15.fileservice.UserInfo\x1a\x1d.fileservice.FileListResponse\x12\x35\n\nFileDelete\x12\x15.fileservice.FileInfo\x1a\x10.fileservice.ack\x12\x37\n\nUpdateFile\x12\x15.fileservice.FileData\x1a\x10.fileservice.ack(\x01\x12@\n\x0fgetClusterStats\x12\x12.fileservice.Empty\x1a\x19.fileservice.ClusterStats\x12;\n\rgetLeaderInfo\x12\x18.fileservice.ClusterInfo\x1a\x10.fileservice.ack\x12\x37\n\x0cMetaDataInfo\x12\x15.fileservice.MetaData\x1a\x10.fileservice.ackb\x06proto3')



_FILEDATA = DESCRIPTOR.message_types_by_name['FileData']
_METADATA = DESCRIPTOR.message_types_by_name['MetaData']
_ACK = DESCRIPTOR.message_types_by_name['ack']
_USERINFO = DESCRIPTOR.message_types_by_name['UserInfo']
_FILEINFO = DESCRIPTOR.message_types_by_name['FileInfo']
_FILELISTRESPONSE = DESCRIPTOR.message_types_by_name['FileListResponse']
_CLUSTERINFO = DESCRIPTOR.message_types_by_name['ClusterInfo']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_CLUSTERSTATS = DESCRIPTOR.message_types_by_name['ClusterStats']
FileData = _reflection.GeneratedProtocolMessageType('FileData', (_message.Message,), {
  'DESCRIPTOR' : _FILEDATA,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.FileData)
  })
_sym_db.RegisterMessage(FileData)

MetaData = _reflection.GeneratedProtocolMessageType('MetaData', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.MetaData)
  })
_sym_db.RegisterMessage(MetaData)

ack = _reflection.GeneratedProtocolMessageType('ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.ack)
  })
_sym_db.RegisterMessage(ack)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), {
  'DESCRIPTOR' : _USERINFO,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.UserInfo)
  })
_sym_db.RegisterMessage(UserInfo)

FileInfo = _reflection.GeneratedProtocolMessageType('FileInfo', (_message.Message,), {
  'DESCRIPTOR' : _FILEINFO,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.FileInfo)
  })
_sym_db.RegisterMessage(FileInfo)

FileListResponse = _reflection.GeneratedProtocolMessageType('FileListResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILELISTRESPONSE,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.FileListResponse)
  })
_sym_db.RegisterMessage(FileListResponse)

ClusterInfo = _reflection.GeneratedProtocolMessageType('ClusterInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTERINFO,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.ClusterInfo)
  })
_sym_db.RegisterMessage(ClusterInfo)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.Empty)
  })
_sym_db.RegisterMessage(Empty)

ClusterStats = _reflection.GeneratedProtocolMessageType('ClusterStats', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTERSTATS,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.ClusterStats)
  })
_sym_db.RegisterMessage(ClusterStats)

_FILESERVICE = DESCRIPTOR.services_by_name['Fileservice']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILEDATA._serialized_start=40
  _FILEDATA._serialized_end=136
  _METADATA._serialized_start=138
  _METADATA._serialized_end=185
  _ACK._serialized_start=187
  _ACK._serialized_end=226
  _USERINFO._serialized_start=228
  _USERINFO._serialized_end=256
  _FILEINFO._serialized_start=258
  _FILEINFO._serialized_end=319
  _FILELISTRESPONSE._serialized_start=321
  _FILELISTRESPONSE._serialized_end=358
  _CLUSTERINFO._serialized_start=360
  _CLUSTERINFO._serialized_end=420
  _EMPTY._serialized_start=422
  _EMPTY._serialized_end=429
  _CLUSTERSTATS._serialized_start=431
  _CLUSTERSTATS._serialized_end=502
  _FILESERVICE._serialized_start=505
  _FILESERVICE._serialized_end=1116
# @@protoc_insertion_point(module_scope)
