# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import fluffy_pb2 as proto_dot_fluffy__pb2


class DataTransferServiceStub(object):
    """a service interface (contract)

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.stream_unary(
                '/fluffy.DataTransferService/UploadFile',
                request_serializer=proto_dot_fluffy__pb2.FileData.SerializeToString,
                response_deserializer=proto_dot_fluffy__pb2.FileInfo.FromString,
                )
        self.DownloadFile = channel.unary_stream(
                '/fluffy.DataTransferService/DownloadFile',
                request_serializer=proto_dot_fluffy__pb2.FileInfo.SerializeToString,
                response_deserializer=proto_dot_fluffy__pb2.FileData.FromString,
                )
        self.ReplicateFile = channel.stream_unary(
                '/fluffy.DataTransferService/ReplicateFile',
                request_serializer=proto_dot_fluffy__pb2.FileData.SerializeToString,
                response_deserializer=proto_dot_fluffy__pb2.FileInfo.FromString,
                )
        self.ListFiles = channel.unary_unary(
                '/fluffy.DataTransferService/ListFiles',
                request_serializer=proto_dot_fluffy__pb2.RequestFileList.SerializeToString,
                response_deserializer=proto_dot_fluffy__pb2.FileList.FromString,
                )


class DataTransferServiceServicer(object):
    """a service interface (contract)

    """

    def UploadFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataTransferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=proto_dot_fluffy__pb2.FileData.FromString,
                    response_serializer=proto_dot_fluffy__pb2.FileInfo.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=proto_dot_fluffy__pb2.FileInfo.FromString,
                    response_serializer=proto_dot_fluffy__pb2.FileData.SerializeToString,
            ),
            'ReplicateFile': grpc.stream_unary_rpc_method_handler(
                    servicer.ReplicateFile,
                    request_deserializer=proto_dot_fluffy__pb2.FileData.FromString,
                    response_serializer=proto_dot_fluffy__pb2.FileInfo.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=proto_dot_fluffy__pb2.RequestFileList.FromString,
                    response_serializer=proto_dot_fluffy__pb2.FileList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fluffy.DataTransferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataTransferService(object):
    """a service interface (contract)

    """

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/fluffy.DataTransferService/UploadFile',
            proto_dot_fluffy__pb2.FileData.SerializeToString,
            proto_dot_fluffy__pb2.FileInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/fluffy.DataTransferService/DownloadFile',
            proto_dot_fluffy__pb2.FileInfo.SerializeToString,
            proto_dot_fluffy__pb2.FileData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicateFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/fluffy.DataTransferService/ReplicateFile',
            proto_dot_fluffy__pb2.FileData.SerializeToString,
            proto_dot_fluffy__pb2.FileInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fluffy.DataTransferService/ListFiles',
            proto_dot_fluffy__pb2.RequestFileList.SerializeToString,
            proto_dot_fluffy__pb2.FileList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
