# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/fileService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/fileService.proto\x12\x0b\x66ileservice\"<\n\x08\x46ileData\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\'\n\x03\x61\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\x08UserInfo\x12\x10\n\x08username\x18\x01 \x01(\t\".\n\x08\x46ileInfo\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"%\n\x10\x46ileListResponse\x12\x11\n\tFilenames\x18\x01 \x01(\t\"<\n\x0b\x43lusterInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\x13\n\x0b\x63lusterName\x18\x03 \x01(\t\"G\n\x0c\x43lusterStats\x12\x11\n\tcpu_usage\x18\x01 \x01(\t\x12\x12\n\ndisk_space\x18\x02 \x01(\t\x12\x10\n\x08used_mem\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\xaa\x04\n\x0b\x46ileservice\x12\x37\n\nUploadFile\x12\x15.fileservice.FileData\x1a\x10.fileservice.ack(\x01\x12>\n\x0c\x44ownloadFile\x12\x15.fileservice.FileInfo\x1a\x15.fileservice.FileData0\x01\x12\x35\n\nFileSearch\x12\x15.fileservice.FileInfo\x1a\x10.fileservice.ack\x12:\n\rReplicateFile\x12\x15.fileservice.FileData\x1a\x10.fileservice.ack(\x01\x12@\n\x08\x46ileList\x12\x15.fileservice.UserInfo\x1a\x1d.fileservice.FileListResponse\x12\x35\n\nFileDelete\x12\x15.fileservice.FileInfo\x1a\x10.fileservice.ack\x12\x37\n\nUpdateFile\x12\x15.fileservice.FileData\x1a\x10.fileservice.ack(\x01\x12@\n\x0fgetClusterStats\x12\x12.fileservice.Empty\x1a\x19.fileservice.ClusterStats\x12;\n\rgetLeaderInfo\x12\x18.fileservice.ClusterInfo\x1a\x10.fileservice.ackb\x06proto3')



_FILEDATA = DESCRIPTOR.message_types_by_name['FileData']
_ACK = DESCRIPTOR.message_types_by_name['ack']
_USERINFO = DESCRIPTOR.message_types_by_name['UserInfo']
_FILEINFO = DESCRIPTOR.message_types_by_name['FileInfo']
_FILELISTRESPONSE = DESCRIPTOR.message_types_by_name['FileListResponse']
_CLUSTERINFO = DESCRIPTOR.message_types_by_name['ClusterInfo']
_CLUSTERSTATS = DESCRIPTOR.message_types_by_name['ClusterStats']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
FileData = _reflection.GeneratedProtocolMessageType('FileData', (_message.Message,), {
  'DESCRIPTOR' : _FILEDATA,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.FileData)
  })
_sym_db.RegisterMessage(FileData)

ack = _reflection.GeneratedProtocolMessageType('ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.ack)
  })
_sym_db.RegisterMessage(ack)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), {
  'DESCRIPTOR' : _USERINFO,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.UserInfo)
  })
_sym_db.RegisterMessage(UserInfo)

FileInfo = _reflection.GeneratedProtocolMessageType('FileInfo', (_message.Message,), {
  'DESCRIPTOR' : _FILEINFO,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.FileInfo)
  })
_sym_db.RegisterMessage(FileInfo)

FileListResponse = _reflection.GeneratedProtocolMessageType('FileListResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILELISTRESPONSE,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.FileListResponse)
  })
_sym_db.RegisterMessage(FileListResponse)

ClusterInfo = _reflection.GeneratedProtocolMessageType('ClusterInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTERINFO,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.ClusterInfo)
  })
_sym_db.RegisterMessage(ClusterInfo)

ClusterStats = _reflection.GeneratedProtocolMessageType('ClusterStats', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTERSTATS,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.ClusterStats)
  })
_sym_db.RegisterMessage(ClusterStats)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'proto.fileService_pb2'
  # @@protoc_insertion_point(class_scope:fileservice.Empty)
  })
_sym_db.RegisterMessage(Empty)

_FILESERVICE = DESCRIPTOR.services_by_name['Fileservice']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILEDATA._serialized_start=40
  _FILEDATA._serialized_end=100
  _ACK._serialized_start=102
  _ACK._serialized_end=141
  _USERINFO._serialized_start=143
  _USERINFO._serialized_end=171
  _FILEINFO._serialized_start=173
  _FILEINFO._serialized_end=219
  _FILELISTRESPONSE._serialized_start=221
  _FILELISTRESPONSE._serialized_end=258
  _CLUSTERINFO._serialized_start=260
  _CLUSTERINFO._serialized_end=320
  _CLUSTERSTATS._serialized_start=322
  _CLUSTERSTATS._serialized_end=393
  _EMPTY._serialized_start=395
  _EMPTY._serialized_end=402
  _FILESERVICE._serialized_start=405
  _FILESERVICE._serialized_end=959
# @@protoc_insertion_point(module_scope)
